apiVersion: v1
kind: Service
metadata:
  name: voltway-web
  namespace: voltway
  labels:
    app.kubernetes.io/name: voltway-web
    app.kubernetes.io/part-of: voltway-demo
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: voltway-web
  ports:
    - name: http
      port: 3000
      targetPort: http
